@cd MovieManager
@echo Deleting files...
@del /Q/S net > nul
@echo Compiling...
javac -d . -target 1.4 -source 1.4 -classpath "%CLASSPATH%";.;lib/skinlf.jar;lib/oalnf.jar;lib/TableLayout.jar;lib/useful.jar;lib/BrowserLauncher2-10rc4.jar;lib/jxl.jar;lib/JNative.jar;lib/retroweaver-all-2.0.jar;lib/commons-httpclient-3.0.1.jar;lib/log4j-1.2.13.jar;lib/commons-beanutils.jar;lib/commons-collections-3.2.jar;lib/commons-digester-1.7.jar;lib/itext-1.4.5.jar;lib/jasperreports-1.2.6.jar;lib/poi-2.5.1-final-20040804.jar;lib/castor-1.0.5.jar;lib/ProportionLayout.jar;lib/driveinfo/sfc.jar;lib/spin.jar;lib\ostermillerutils_1_05_00_for_java_1_4.jar source/net/sf/xmm/moviemanager/*.java source/net/sf/xmm/moviemanager/database/*.java source/net/sf/xmm/moviemanager/swing/extentions/*.java source/net/sf/xmm/moviemanager/swing/util/table/*.java source/net/sf/xmm/moviemanager/fileproperties/*.java source/net/sf/xmm/moviemanager/util/*.java source/net/sf/xmm/moviemanager/http/*.java source/net/sf/xmm/moviemanager/models/*.java source/net/sf/xmm/moviemanager/commands/*.java source/net/sf/xmm/moviemanager/mediainfodll/*.java
@cd ..
